# Copyright (c) 2024 Microchip Technologies
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: pic64gx-zephyrproject-rtos
      url-base: https://github.com/pic64gx

  projects:
    - name: pic64gx-zephyr
      remote: pic64gx-zephyrproject-rtos
      revision: 799c3f61f89e5602212b5cfc7de5f5e630de90f1
      path: zephyr
      import:
        name-allowlist:
          - hal_microchip
          - open-amp
          - libmetal
